---
- name: Include all yml variables in vars/all
  ansible.builtin.include_vars:
    dir: vars/hosts
    extensions:
      - 'yml'

- name: Include lvm-create.yml
  ansible.builtin.import_tasks: lvm-create.yml
 
- name: Include preconf.yml
  ansible.builtin.import_tasks: preconf.yml

- name: Include validate.yml
  ansible.builtin.import_tasks: validate.yml

- name: Include clean.yml
  ansible.builtin.import_tasks: clean.yml
  when: (db_stop is defined and db_stop == '1') or (db_init is defined and db_init == '1')


##  Percona Tools
##  =============

- name: Adds percona key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
    state: present
  with_items:
    - E1E2CD202D607DAF
    - 1C4CBDCDCD2EFD2A
    - 9334A25F8507EFA5
    - 9E003FA64CAC6D72

- name: Add Percona apt repository
  apt:
    deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release | lower }}_all.deb"
    update_cache: true
    state: present


- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: Install mysql-client
  ansible.builtin.apt:
    name: mysql-client
    state: present

- name: Install Xtrabackup
  ansible.builtin.apt:
    name: percona-xtrabackup-24
    state: present

# Percona Toolkit

- name: Install Percona Toolkit
  package:
    name: percona-toolkit
    state: present


##  Other Packages
##  ==============

- name: Install socat
  tags: [ mariadb-galera ]
  package:
    name: socat
    state: present


##  Prepare MariaDB installation
##  ==========================

- name: Ensure group MySQL exists
  ansible.builtin.group:
    name: mysql
    state: present

- name: Add mysql user
  user:
    name: "{{ mysql_user }}"
    comment: MariaDB daemon
    group: "{{ mysql_group }}"
    create_home: no
    shell: /sbin/nologin
    state: present

- name: Create scripts dir
  file:
    path: "{{ script_dir }}"
    state: directory

- name: Copy get-tarball.sh and config-get-tarball.sh
  copy:
    src: "./files/{{ item }}"
    dest: "{{ script_dir }}"
    owner: root
    group: root
    mode: 'preserve'
  with_items:
    - get-tarball.sh
    - config-get-tarball.sh

# Returns code 100 if the tarball was unpacked.
# This check can be used later to check if new MariaDB was put in place:
# get_tarball.rc == 100
- name: Run get-tarball.sh
  shell: >
    "{{ script_dir }}/get-tarball.sh"
  register: get_tarball
  failed_when: get_tarball.rc != 0 and get_tarball.rc != 100

- name: Create MariaDB basedir
  file:
    path: "{{ mysql_base_dir }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    recurse: yes
    state: directory
  when: get_tarball.rc == 100

# We separate directory creation and permissions
# because we only want to know if datadir was created
# to determine if mysqld --initialize should be run.

- name: Create MariaDB datadir
  file:
    path: "{{ mysql_data_dir }}"
    state: directory
  register: datadir
  when: get_tarball.rc == 100

- name: Set MariaDB datadir permissions
  file:
    path: "{{ mysql_data_dir }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: '777'
  when: get_tarball.rc == 100

- name: Create MariaDB log dir
  file:
    path: "{{ mysql_log_dir }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: '764'
    recurse: yes
    state: directory
  when: get_tarball.rc == 100

- name: Create MariaDB temp dir
  file:
    path: "{{ mysql_tmp_dir }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: '755'
    state: directory
  when: get_tarball.rc == 100

- name: Create MariaDB run dir (socket, PID)
  file:
    path: "{{ mysql_run_dir }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: '755'
    state: directory
  when: get_tarball.rc == 100

- name: Add lib to ld.so.conf
  lineinfile:
    dest=/etc/ld.so.conf
    line="{{ mysql_base_dir }}/lib/"
  when: get_tarball.rc == 100

- name: ldconfig
  command: /sbin/ldconfig
  when: get_tarball.rc == 100


# Create config dir and copy general config file and host config file

- name: Create MariaDB configuration dir
  file:
    path: "{{ mysql_conf_dir }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: '777'
    state: directory
  when: get_tarball.rc == 100

- name: Delete files/dirs not created by us
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/mysql/conf.d
    - /etc/mysql/my.cnf.fallback
    - /etc/mysql/percona-server.cnf
    - /etc/mysql/percona-server.conf.d

- name: Copy my.cnf
  template:
    src="./templates/config-groups/{{ primary_config_group }}.cnf.j2"
    dest=/etc/mysql/my.cnf

- name: Create configuration include subdir
  file:
    path: "{{ mysql_conf_dir }}/include"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: '777'
    state: directory

- name: Copy wsrep.cnf (first node)
  template:
    src="./templates/wsrep/first_node.cnf.j2"
    dest=/etc/mysql/include/wsrep.cnf
  when: inventory_hostname == cluster_hosts[0].node_name

- name: Copy wsrep.cnf (default)
  template:
    src="./templates/wsrep/default.cnf.j2"
    dest=/etc/mysql/include/wsrep.cnf
  when: 
    - inventory_hostname in groups["nodo_n"]

- name: Check if host config file exists
  local_action: stat path="/etc/mysql/{{ inventory_hostname }}.cnf"
  register: host_config_file

- name: Copy host config file if exists
  template:
    src="./templates/config-hosts/{{ inventory_hostname }}.cnf.j2"
    dest="/etc/mysql/{{ inventory_hostname }}.cnf"
  when: host_config_file.stat.exists == true



# Running mysqld --initialize with non-empty directory should be safe,
# because it is supposed to fail. But not to rely on this is better.
# Also, it would be problematic to check if the command succeeded.
# So first we use a BASH command to get the number of files in the datadir.
- name: Check if datadir is empty
  shell: >
    ls -1 "{{ mysql_data_dir }}" |wc -l
  register: datadir_file_count

- name: Initialize datadir
  command: "{{ mysql_base_dir }}/bin/mysqld --initialize --user='{{ mysql_user }}'"
  ignore_errors: yes
  when: datadir_file_count.stdout == '0'

- name: Fix MariaDB datadir and log dir permissions
  file:
    path: "{{ item }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: '774'
    recurse: yes
  with_items:
    - "{{ mysql_data_dir }}"
    - "{{ mysql_log_dir }}"

- name: Add MariaDB bin path to profile
  lineinfile: dest=/etc/profile line="export PATH=$PATH:{{ mysql_base_dir }}/bin/"

- name: Add custom scripts path to profile
  lineinfile: dest=/etc/profile line="export PATH=$PATH:{{ script_dir }}"
  when: get_tarball.rc == 100

- name: Run profile
  shell: executable=/bin/bash source /etc/profile
  when: get_tarball.rc == 100

- name: Copy mysql.server
  template:
    src=./templates/mysql.server.j2
    dest=/etc/init.d/mysql.server
  register: mysql_service

- name: Fix mysql.server permissions
  file:
    path: /etc/init.d/mysql.server
    owner: root
    group: root
    mode: '755'
  when: mysql_service.changed

- name: Reload service
  command: systemctl daemon-reload
  when: mysql_service.changed

- name: Restart mysql
  service:
    name=mysql
    state=restarted
  when: inventory_hostname == cluster_hosts[0].node_name

- import_tasks: mysql-initial-queries.yml

- name: Copy wsrep.cnf to the first node
  template:
    src="./templates/wsrep/default.cnf.j2"
    dest=/etc/mysql/include/wsrep.cnf
  when:
    - inventory_hostname == cluster_hosts[0].node_name
    - cluster_hosts|length > 0


##  Logrotate
##  =========

- name: Create mysql_logrotate_old_dir
  file:
    path: "{{ mysql_logrotate_old_dir }}"
    owner: mysql
    group: mysql
    mode: '770'
    state: directory

- name: Configure logrotate
  template:
    src: "../templates/logrotate.j2"
    dest: "/etc/logrotate.d/mysql"


##  Timezone Info
##  =============

- name: Update timezone info (first node)
  apt:
    name: tzdata
    state: latest
    install_recommends: no
  register: timezone_info
  when: inventory_hostname == cluster_hosts[0].node_name

- name: Restart mysql
  service:
    name=mysql
    state=restarted
  when: 
    - inventory_hostname in groups["nodo_n"]

- import_tasks: pre-mysql-exporter.yml

- import_tasks: install-mysql-exporter.yml

- import_tasks: hardening.yml

