---

##- name: Get Password MariaDB
## shell: cat /var/log/mysql/error/error.log | grep -i "A temporary password is generated for" | awk '{print$11}' | tail -1
##  ignore_errors: true
##  register: securepass
##  when: inventory_hostname == cluster_hosts[0].node_name

##- name: Output world writable files
##  ansible.builtin.debug:
##    var: securepass.stdout_lines[0]
##  when: inventory_hostname == cluster_hosts[0].node_name

- name: Change Password MariaDB
  shell: |
    mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ superuser_password }}'"
  ignore_errors: true
  when: inventory_hostname == cluster_hosts[0].node_name

- name: Create Xtrabackup User
  shell: |
    mysql -u root -p"{{ superuser_password }}" -e "CREATE USER '{{ xtrabackup_mysql_user }}'@'%' IDENTIFIED BY '{{ xtrabackup_mysql_password }}'"
    mysql -u root -p"{{ superuser_password }}" -e "GRANT ALL PRIVILEGES ON * . * TO '{{ xtrabackup_mysql_user }}'@'%'"
  when: inventory_hostname == cluster_hosts[0].node_name
