---

- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: Update apt-get repo and cache
  ansible.builtin.apt:
    name: iptables
    state: present

##  Ports
##  =====

- name: Open some ports to the world
  tags: [ linux-for-mariadb, iptables ]
  iptables:
    chain: "{{ item[1] }}"
    protocol: "{{ item[0].protocol }}"
    match: "{{ item[0].protocol }}"
    destination_port: "{{ item[0].port }}"
    jump: ACCEPT
  with_nested:
    - "{{ world_allowed_ports }}"
    - "{{ chains }}"


##  Optimisation
##  ============

- name: Set Kernel parameters
  tags: [ linux-for-mariadb, kernel-parameters ]
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
  with_items: "{{ kernel_parameters }}"


##  Languages
##  =========

- name: Install Perl
  tags: [ linux-for-mariadb, perl-upgrade ]
  package:
    name: perl
    state: latest

- name: Install Python3
  tags: [ linux-for-mariadb, python-upgrade ]
  package:
    name:
      - python3
      - python3-pymysql
    state: latest


##  Tools
##  =====


- name: Install packages that are useful to investigate performance
  tags: [ linux-for-mariadb ]
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ package_list }}"
